// import { Roboto } from "next/font/google";
// import "@/app/globals.css";
// import Header from "@/pages/Header";
// import Footer from "@/pages/Footer";

// const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

// export default function RootLayout({ children }) {
//   return (
//     <div className={roboto.className}>
//       <Header />
//       {children}
//       <Footer />
//     </div>
//   );
// }

import { Inter } from "next/font/google";
import "../app/globals.css";
import Header from "@/pages/Header";
import Footer from "@/pages/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "RngrangHungul",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <>
      <Header />
      {children}
      <Footer />
    </>
  );
}
